CC				= 	m68k-atari-mint-gcc
AR				= 	m68k-atari-mint-ar
RANLIB			= 	m68k-atari-mint-ranlib
STACK			= 	m68k-atari-mint-stack
STRIP			=	m68k-atari-mint-strip
COMPRESS		= 	upx
INCLUDE_PATH	= 	/usr/local/include
LIB_PATH		= 	/usr/local/lib
STACKSIZE		= 	256k
OPTIMISATION	= 	-O2 -fomit-frame-pointer
C_CPU			= 	-m68020-60
LIB				= 	-lgem -lldg
CFLAGS			= 	$(DEBUG) $(C_CPU) $(OPTIMISATION) -DDEBUG -DUSE_ASM -Wall -Wshadow -I$(INCLUDE_PATH)

DESK_OBJ		= 	desktop/desktop.o desktop/scan_desktop.o
RASTER_OBJ		= 	raster/resample.o raster/color.o raster/dither.o				\
					raster/raster.o raster/pixel.o raster/vdi.o
FORM_OBJ		= 	form/alert.o form/about.o form/info.o
ICON_OBJ		= 	icon/set_icon.o icon/draw_icon.o
FILE_OBJ		= 	file/sort.o file/file.o file/rename.o file/get_disk_size.o
WINFILE_OBJ		= 	winfile/WinFile_New.o winfile/WinFile_Tab.o winfile/WinFile_Update_Icon_Position.o	\
					winfile/WinFile_Calc_Areas.o winfile/WinFile_Iconify.o winfile/WinFile_Slider.o 	\
					winfile/WinFile_Other_Event.o winfile/WinFile_Close.o 			\
					winfile/WinFile_Entry.o winfile/WinFile_Mouse.o 				\
					winfile/WinFile_Exec_Entry.o winfile/WinFile_Sizer.o winfile/WinFile_Popup.o		\
					winfile/WinFile_Rubberbox.o winfile/WinFile_Frame_Sizer.o winfile/WinFile_Keyb.o 	\
					winfile/WinFile_Infobar.o winfile/WinFile_Tabbar.o winfile/WinFile_Redraw.o

OBJ 			=	$(RASTER_OBJ) $(FILE_OBJ) $(ICON_OBJ) $(WINFILE_OBJ)			\
					$(FORM_OBJ) $(DESK_OBJ) misc.o debug.o custom_font.o			\
					ztext.o appl.o codecs.o mfdb.o mem.o pic_load.o	rename_entry.o	\
					edit.o prefs.o menu.o evnt_loop.o main.o

PROGRAM 		= 	zdesk.app

OBJDIR			=	.obj
OBJECTS			=	$(addprefix $(OBJDIR)/,$(OBJ))



.SUFFIXES:
.SUFFIXES: .c .s .o

# all: $(PROGRAM) stack strip compress
all: $(PROGRAM) stack

$(OBJDIR)/%.o: %.c $(OBJDIR)
	@echo CC $(notdir $@)
	@cp $*.c tmppc.c
	@$(CC) $(CFLAGS) -otmppc.o -c tmppc.c
	@mv -f tmppc.o $(OBJDIR)/$(notdir $*.o)
	@rm -f tmppc.c

$(PROGRAM): $(OBJECTS)
	$(CC) $(C_CPU) -o$@ $(addprefix $(OBJDIR)/,$(notdir $(OBJ))) -s -L$.. -L$(LIB_PATH) $(LIB)

$(OBJDIR):; mkdir $(OBJDIR)

strip:
	$(STRIP) $(PROGRAM)

stack:
	$(STACK) -S $(STACKSIZE) $(PROGRAM)

compress:
	$(COMPRESS) $(PROGRAM)

clean:
	rm -f $(OBJDIR)/*.o tmppc.c
	rmdir $(OBJDIR)

